"""Controlled nail-domain vocabulary used for validation and deterministic parsing.

Sources: audited style-analysis schemas and memory notes of the predecessor
Lunelle projects (nail-style-recognizer / nail-style-prompt-builder skills).
"""

from __future__ import annotations

SHAPES = (
    "almond",
    "coffin",
    "square",
    "tapered-square",
    "squoval",
    "oval",
    "round",
    "stiletto",
)
DEFAULT_SHAPE = "almond"

LENGTHS = ("short", "medium", "long", "extra-long")
DEFAULT_LENGTH = "medium"

SKIN_TONES = ("light", "medium", "tan", "deep")
DEFAULT_SKIN_TONE = "light"

FINISHES = (
    "glossy",
    "matte",
    "jelly",
    "chrome",
    "glitter",
    "translucent",
    "milky",
    "pearl",
    "cat-eye",
    "velvet",
    "marble",
    "magnetic",
)

# keyword -> canonical shape
SHAPE_KEYWORDS = {
    "almond": "almond",
    "coffin": "coffin",
    "ballerina": "coffin",
    "square": "square",
    "tapered square": "tapered-square",
    "tapered-square": "tapered-square",
    "squoval": "squoval",
    "oval": "oval",
    "round": "round",
    "stiletto": "stiletto",
    "杏仁": "almond",
    "梯形": "coffin",
    "芭蕾": "coffin",
    "方形": "square",
    "方圆": "squoval",
    "椭圆": "oval",
    "圆形": "round",
    "尖形": "stiletto",
}

LENGTH_KEYWORDS = {
    "extra long": "extra-long",
    "extra-long": "extra-long",
    "xl": "extra-long",
    "超长": "extra-long",
    "long": "long",
    "长款": "long",
    "长": "long",
    "medium": "medium",
    "中长": "medium",
    "中等": "medium",
    "short": "short",
    "短款": "short",
    "短": "short",
}

COLOR_KEYWORDS = (
    "milky white",
    "off white",
    "white",
    "cream",
    "ivory",
    "nude",
    "beige",
    "champagne",
    "soft pink",
    "baby pink",
    "hot pink",
    "blush pink",
    "pink",
    "rose",
    "red",
    "burgundy",
    "wine",
    "coral",
    "peach",
    "orange",
    "yellow",
    "gold",
    "mint",
    "sage",
    "green",
    "emerald",
    "teal",
    "sky blue",
    "baby blue",
    "navy",
    "blue",
    "lavender",
    "lilac",
    "purple",
    "violet",
    "brown",
    "coffee",
    "chocolate",
    "taupe",
    "gray",
    "grey",
    "silver",
    "black",
    "smoke",
    "charcoal",
)

ELEMENT_KEYWORDS = (
    "french tip",
    "micro french",
    "double french",
    "pearl",
    "gold line",
    "gold foil",
    "silver line",
    "rhinestone",
    "crystal",
    "gem",
    "diamond",
    "stud",
    "charm",
    "chain",
    "bow",
    "heart",
    "star",
    "moon",
    "butterfly",
    "flower",
    "floral",
    "rose",
    "daisy",
    "leaf",
    "leopard",
    "zebra",
    "cow print",
    "plaid",
    "tartan",
    "lace",
    "gradient",
    "ombre",
    "aura",
    "aurora",
    "marble",
    "tortoise",
    "flame",
    "wave",
    "swirl",
    "polka dot",
    "dot",
    "stripe",
    "pinstripe",
    "glitter",
    "sequin",
    "3d charm",
    "airbrush",
    "smiley",
    "cherry",
    "strawberry",
    "snowflake",
)

FINISH_KEYWORDS = {
    "glossy": "glossy",
    "gloss": "glossy",
    "shiny": "glossy",
    "matte": "matte",
    "jelly": "jelly",
    "translucent": "translucent",
    "sheer": "translucent",
    "milky": "milky",
    "chrome": "chrome",
    "metallic": "chrome",
    "mirror": "chrome",
    "glitter": "glitter",
    "shimmer": "glitter",
    "pearl": "pearl",
    "pearlescent": "pearl",
    "cat eye": "cat-eye",
    "cat-eye": "cat-eye",
    "velvet": "velvet",
    "marble": "marble",
    "magnetic": "magnetic",
    "亮面": "glossy",
    "磨砂": "matte",
    "哑光": "matte",
    "果冻": "jelly",
    "猫眼": "cat-eye",
    "珠光": "pearl",
}

DEFAULT_BASE_COLORS = ["nude pink"]
DEFAULT_VISUAL_STYLE = "elegant e-commerce product photography"
